### ISSUE TITLE
Possible grid size bug on smaller screens

### ISSUE THREAD

**Issue by justpie** [gmaps-marker-clusterer/gmaps-marker-clusterer#36] opened 2017-05-04 14:52 UTC
I noticed that if you set a large grid size ( 200 ) and navigate to the application with a device that uses a smaller screen such as a phone ( iphone 6s ) the clusters behave strangely. When you click the cluster the first time it recenters the map on that cluster but doesn't zoom or expand the cluster. When you try to click it again the cluster just disappears. If I manually zoom on the map the cluster expands and zooming out makes the cluster appear again. 

Thanks!

**Comment by XmlmXmlmX** [comment] 2017-05-08 08:01
Hi, thank you for your report. Could you please add a example, like a [fiddle](https://www.jsfiddle.net) or [codepen](https://codepen.io/).

**Comment by Remo** [comment] 2017-07-19 19:38
@justpie I'm going to close this since we couldn't reproduce it. If you create a fiddle or codepen we'd be happy to have another look.

**Closed by Remo** 2017-07-19 19:38 UTC
